config/routes.rb
Rails.application.routes.draw do
  default_url_options host: ENV.fetch('HOST') { 'localhost' }, port: ENV.fetch('PORT') { '3000' }

  root 'users/link_managements#index'

  resources :links, controller: 'users/link_managements', as: :links

  namespace :api do
    namespace :users do
      resources :links, only: [:index], controller: 'link_managements',
                        as: :links,
                        defaults: { format: :json },
                        constraints: ->(request) { %w[application/json].include?(request.headers['Content-Type']) } do
        collection do
          post '/generate-short-url', action: :generate_short_url, as: :generate_short_url
        end
      end
    end
  end

  devise_for :users, path: 'auth', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'sign-up'
  }

  get '/:short_path', to: 'users/link_managements#redirect',
                      as: :redirect_original,
                      constraints: ->(request) { request.params[:short_path].length >= NUM_OF_SHORT_URL_CHAR }

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  field :email,              type: String
  field :encrypted_password, type: String
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time
  field :remember_created_at, type: Time
  field :api_key, type: String, default: -> { Utils::ApiKeyGenerator.encode(email: email) }

  ## Relation
  has_many :links, dependent: :destroy

  ## Static indexes
  index({ email: 1 }, { unique: true, name: "email_index" })
  index({ api_key: 1 }, { unique: true, name: "api_key_index" })
end

app/controllers/api/users/link_managements_controller.rb
module Api
  module Users
    class LinkManagementsController < Api::ApplicationController
      def index
        json_response(paginated_serialize(collection))
      end

      def generate_short_url
        ::Users::Links::CreateService.call(parameters.merge(user: current_user)) do |operation|
          operation.success { |data| json_response(serialize(data), status: :created) }
          operation.failure { |error| json_error_response(error, status: 422) }
        end
      end

      private

      def collection
        current_user.links
      end

      def serializer
        ::LinkSerializer
      end
    end
  end
end

app/controllers/users/link_managements_controller.rb
module Users
  ##
  # Users::LinkManagementsController
  ##
  class LinkManagementsController < ApplicationController
    before_action :set_link, only: [:show, :edit, :update, :destroy]

    def index
      @links = resources
    end

    def show; end

    def new
      @link = Link.new
    end

    def edit; end

    # rubocop:disable Metrics/MethodLength
    def create
      ::Users::Links::CreateService.call(parameters.merge(user: current_user)) do |operation|
        operation.success do |data|
          @link = data
          redirect_to links_path, notice: "Link management was successfully created."
        end

        operation.failure do |errors|
          @link = Link.new
          @errors = build_errors_message(errors)
          render :new, status: :unprocessable_entity
        end
      end
    end
    # rubocop:enable Metrics/MethodLength

    def update
      ::Users::Links::UpdateService.call(parameters.merge(resource: @link)) do |operation|
        operation.success do |data|
          @link = data
          redirect_to links_path, notice: "Link management was successfully created."
        end

        operation.failure do |errors|
          @errors = build_errors_message(errors)
          render :edit, status: :unprocessable_entity
        end
      end
    end

    def destroy
      @link.destroy

      redirect_to links_url, notice: "Link management was successfully destroyed."
    end

    def redirect
      @link = Link.find_by(short_path: params[:short_path])

      @link.inc(num_of_click: 1)

      redirect_to @link.original_url
    rescue Mongoid::Errors::DocumentNotFound
      raise ActionController::RoutingError.new('Not Found', 404)
    end

    private

    def resources
      @resources ||= current_user.links
    end

    def set_link
      @link = resources.find(params[:id])
    end
  end
end

app/helpers/api/users/link_managements_helper.rb
module Api
  module Users
    module LinkManagementsHelper
    end
  end
end

app/helpers/users/link_managements_helper.rb
module Users
  module LinkManagementsHelper
    def generate_actions(resource)
      element = <<-HTML
      <div class="actions">
        <a href="#{edit_link_path(resource)}"><i class="fa fa-pencil"></i></a>
        <a href="#{link_path(resource)}" data-method="delete"><i class="fa fa-trash"></i></a>
      </div>
      HTML

      element.html_safe
    end
  end
end

app/views/users/link_managements/_form.html.erb
<div class="links links-form col-md-6">
  <h4 class="breadcrumbs">
    New link
    <%= link_to 'Back', root_path %>
  </h4>
    
  <%= form_with(model: link) do |form| %>
    <% if @errors&.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@errors.count, "error") %> prohibited this link from being saved:</h2>

        <ul>
          <% @errors.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, placeholder: 'Ex: Test link', class: "form-control" %>
    </div>

    <div class="field">
      <%= form.label :original_url %>
      <%= form.text_field :original_url, placeholder: 'Ex: https:// or http://', class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "Save", class: "btn btn-primary btn-block" %>
    </div>
  <% end %>
</div>

app/views/users/link_managements/edit.html.erb
<%= render 'form', link: @link %>

app/views/users/link_managements/index.html.erb
<div class="col-md-12 links">
  <h4 class="breadcrumbs">
    Links Management 
    <%= link_to 'New link', new_link_path %>
  </h4>

  <table class="table mt-3 data-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Original URL</th>
        <th>Short URL</th>
        <th>Clicked</th>
        <th>Created at</th>
        <th>Action</td>
      </tr>
    </thead>
    <tbody>
      <% @links.each do |link| %>
        <tr>
          <td><%= link.name %></td>
          <td><%= link.original_url %></td>
          <td><%= link_to link.short_url, link.short_url %></td>
          <td><%= link.num_of_click %></td>
          <td><%= link.created_at %></td>
          <td><%= generate_actions(link) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/link_managements/new.html.erb
<%= render 'form', link: @link %>

app/views/users/link_managements/show.html.erb
<div class="col-md-6 links center-container">
  <div class="card">
    <div class="card-body">
      <p><%= link_to 'Back', :back %></p>
      <p><b>Name:</b> <%= @link.name %></p>
      <p><b>Original URL:</b> <%= @link.original_url %></p>
      <p><b>Short URL:</b> <%= link_to @link.short_url, @link.short_url %></p>
    </div>
    <div class="float-right text-right pr-2"><%= generate_actions(@link) %></div>
  </div>
</div>